### ISSUE TITLE
Create an example project for feature Redis

### ISSUE THREAD

**Issue by 0xCAB0** [ThalosES/vinted-rs#119]
Add an example Rust project that uses the Redis feature. 

### Tasks required

- [ ] Sample project README
- [ ] Add the project to Cargo workspace
- [ ] Use the re-exported Redis and Redis-macros crates
